import "./globals.css";
import "@ant-design/v5-patch-for-react-19";
import { AntdRegistry } from "@ant-design/nextjs-registry";
import { Be_Vietnam_Pro } from "next/font/google";

const beVietnamPro = Be_Vietnam_Pro({
  subsets: ["latin", "vietnamese"],
  weight: ["400", "500", "700"], // Thay đổi theo nhu cầu
  variable: "--font-be-vietnam-pro", // Tạo biến CSS
});

export const metadata = {
  title: "Dropii FE Intership Test",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="vi">
      <body className={beVietnamPro.variable}>
        <AntdRegistry>{children}</AntdRegistry>
      </body>
    </html>
  );
}
